config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'

  get 'chats/show'

  get 'chats/showParticipants'

  get 'home/index'
  root 'home#index'
  resources :messages, only: [:create]
  resources :participants, only: [:new, :create]
  resources :chatrooms
  delete 'participants/destroy'

  devise_for :user

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
  has_many :messages

  def get_Messages
    messages = Message.where(chatroom_id: id)
    return messages
  end

  def getParticipants
    participants = Participant.where(chatroom_id: id)
    return participants
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chatroom_messages
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # has_many :chatrooms
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :messages

  def get_chats
    chatroom_ids = Participant.where(user_id: id).pluck(:chatroom_id)
    chats = []
    chatroom_ids.each do|cid|
      chats.push(Chatroom.find(cid))
    end
    return chats
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def show
    chat = Chatroom.find(params[:id])
    @chatTitle = chat.name
    @messages = chat.get_Messages
    @message = Message.new
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        p = Participant.new
        p.chatroom_id = @chatroom.id
        p.user_id = current_user.id
        p.save
        format.html { redirect_to "/", notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    chat = Chatroom.find(params[:id])
    @chatTitle = chat.name
    @messages = chat.get_Messages
    @message = Message.new
  end

  def showParticipants
    chat = Chatroom.find(params[:id])
    @participants = chat.getParticipants
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @chats = current_user.get_chats
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user!
  respond_to :html, :js

  def create
    # @message = Message.new(message_params)
    # @message.user_id = current_user.id
    # respond_to do |format|
    #   if @message.save
    #     format.html{ return redirect_to :back  }
    #     format.js {   }
    #     format.json { render :show, status: :created, location: @post }
    #   else
    #     format.html { render 'home/index' }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    respond_to do |format|
      if @message.save
        sync_new @message
        format.js{ }
      end
    end

    respond_with { @message }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:content, :chatroom_id)
  end

  def authorize_user
    if current_user!= @message.user
      return redirect_to '/'
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
    @participant.chatroom_id = params[:chatroom_id]
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)
    respond_to do |format|
      if @participant.save
        format.html { redirect_to chats_show_path(id: @participant.chatroom_id), notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.where(user_id: params[:user_id], chatroom_id: params[:chatroom_id])[0]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:chatroom_id,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/chat/show.html.erb
<h1><%=@chatTitle%></h1>
<%= render 'message/messageform', message: @message, chatroom_id: params[:id]%>
<%@messages.each do |m|%>
  <p><b><%=m.user.email%> : </b><%=m.content%></p>
<%end%>

app/views/chatrooms/_form.html.erb
<%= form_for(@chatroom) do |f| %>
  <% if @chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% @chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form' %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chatroom_path(@chatroom) %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chats/show.html.erb
<h1><%=@chatTitle%></h1>
<div>
  <%= link_to "Show All Members", chats_showParticipants_path(:id => params[:id])%>
  <%=link_to "Add Member",new_participant_path(:chatroom_id => params[:id])%>
</div>


<%= sync partial: 'message_row', collection: @messages %>
<%= sync_new partial: 'message_row', resource: Message.new %>


<%= render 'messages/messageform', message: @message, chatroom_id: params[:id]%>

app/views/chats/showParticipants.html.erb
<% @participants.each do |p| %>
  <p><%=p.user.email%> <%=link_to "Remove User",participants_destroy_path(:user_id => p.user.id,:chatroom_id=> p.chatroom_id), method: :delete%></p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome <%=current_user.email%></h1>
<%= link_to "Create new chatroom", new_chatroom_path%>
<%@chats.each do |chat|%>
  <p><%= link_to chat.name , controller: "chats", action: "show", id: chat.id%></p>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_sync_config %>
</head>
<body>

<% if user_signed_in?%>
  <%=link_to 'Signout', destroy_user_session_path, method: :delete%>
  <%= link_to 'Home', root_path%>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/messages/_message_row.html.erb
<p><b><%=m.user.email%> : </b><%=m.content%></p>

app/views/messages/_messageform.html.erb
<%= form_for @message, remote: true do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>

      <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Type a message"%>
  </div>
  <%= f.hidden_field :chatroom_id, value: chatroom_id %>
  <div class="actions message_send_button">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/create.js.erb
$('textarea#message_content').val('');

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.telephone_field :user_id %>
  </div>
  <%= f.hidden_field :chatroom_id, value: params[:chatroom_id]%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>
<%= render 'participants/form' %>

<%= link_to 'Back', :back%>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/sync/messages/_message_row.html.erb
<p><b><%=message.user.email%> : </b><%=message.content%></p>